# Generated by Django 4.2.4 on 2023-08-16 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('specialty', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('account_no', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('tel', models.CharField(max_length=15)),
                ('picture', models.BinaryField()),
                ('resume_file', models.BinaryField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
